### ISSUE TITLE
Alias or Rename this Module to be "callbag-from-iterator"

### ISSUE THREAD

**Issue by simplygreatwork** [staltz/callbag-from-iter#2]
I think you would agree.

- Philip

**Comment by simplygreatwork** [comment]
I'd suggest the same for "callbag-from-obs" -> "callbag-from-observable". No issue tickets are available in that repository so I'm commenting here.

**Comment by staltz** [comment]
The reason why it's called `from-iter` is that it supports **both** Iterable and Iterator, so the name `callbag-from-iterator` would be functionally incorrect.
